### PR TITLE
Organizing Processing

### PR DESCRIPTION
**Pull request by jacobjoaquin**
- Created a new top-level folder called "processing", the purpose being to house all processing projects that ship with the package.
- Moved the existing processingDemo into processing
- Created a new "fireworksDemo" which does the following:
  - Moves the vst code into a new class.
  - Replaces custom classes and code with existing Processing classes and code. ie PVector.
  - Renders the images on screen based on the contents of the vst buffer.

### CODE REVIEW

**Comment by osresearch** [comment]
Does it make sense to package the serial, clipping and displayable bits into a processing library of some sort? I'm worried that we have two (three, actually, since tennis for two is still there) implementations of the serial port code, the vector line code, etc.

**Comment by osresearch** [comment]
(the fireworks look pretty good on the vectrex! they are a little slow when the screen is full and might benefit from adding vector sorting to the displayable class)

**Comment by jacobjoaquin** [comment]
## Changes

### fireworksDemo
- Consolidated the following into VST.pde:
  - Clipping.pde
  - VstBuffer.pde
- Added sort to class VstBuffer
  - This is a first pass, but benchmarks has shown 20% to 80% reduction in drawing / moving distance. The more firework sparks on screen, the higher the reduction.
- VstBuffer
  - Now extends from ArrayList<Byte>. This made it easier to sort.
- Bugs and Optimizations
  - There might be bugs
  - Sort could be optimized in terms of Processing efficiency and vector drawing efficiency. Though hopefully "good enough" for now

## Potential Changes
- Support Processing translation / scale / rotation matrix
- Rename `Vst.vline` to `Vst.line`.
  - This would require pass (this) when instantiating Vst.
  - ie `vst = new Vst(this, createSerial)'
- Add `Vst.beginShape()` and `Vst.endShape()`
  - For creating sending continuous shapes.
  - More efficient sends in buffer output as less transit/bright/z command

**Comment by jacobjoaquin** [comment]
## Updates
- Matrix Transforms work
  - Tested with `pushMatrix()`, `popMatrix()`, `translate()`, `scale()`, `rotate()`
- Flag `Vst.displayTransit`
  - Draws the full path of the transit.
  - Defaults to false.
- Sort fixed
  - Forget to swap the bright commands for the endpoints.
- `Vst.rect()`
  - Draws a rectangle.
  - Respondes to `rectMode(CENTER)` and `rectMode(CORNER)`
- `Vst.vline()` is now `Vst.line()`.
- Added basic demo
  - This is nearly the simplest demo possible.
  - It's easy to get up and running from a Processing standpoint.
- Vst stroke color for bright, normal, and transit updated.
  - Members (with defaults):
    - `color colorNormal = color(0, 80);`
    - `color colorBright = color(0);`
    - `color colorTransit = color(255, 0, 0);`

**Comment by osresearch** [comment]
I'm going to merge this since it doesn't change the `processingDemo/` directory and we can check point the progress thus far.  I like the idea of overriding `line()`, `elipse()`, etc and having the entire scene drawn by the `Vst` class.

**Pull request merged**
